
[tool.black]
line-length = 88
target-version = ['py312']
exclude = '''
/(
  \.git
  | \.venv
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true

[tool.mypy]
python_version = "3.12"
strict = true
warn_unused_ignores = true
show_error_codes = true
check_untyped_defs = true
no_implicit_optional = true
disallow_untyped_decorators = false
disallow_untyped_defs = true
ignore_missing_imports = true